"""modify Notes table properties names

Revision ID: 625afa1fc17e
Revises: 331e000977cf
Create Date: 2022-11-12 16:25:40.052663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '625afa1fc17e'
down_revision = '331e000977cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('title', sa.String(length=500), nullable=True))
    op.add_column('notes', sa.Column('content', sa.String(length=10000), nullable=True))
    op.drop_column('notes', 'name')
    op.drop_column('notes', 'data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('data', sa.VARCHAR(length=10000), nullable=True))
    op.add_column('notes', sa.Column('name', sa.VARCHAR(length=500), nullable=True))
    op.drop_column('notes', 'content')
    op.drop_column('notes', 'title')
    # ### end Alembic commands ###
